package com.rendevu.main;

import android.app.AlertDialog;
import android.app.DialogFragment;
import android.app.LauncherActivity;
import android.os.Bundle;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.LayoutInflater;
import android.view.TextureView;
import android.view.View;
import android.view.ViewGroup;
import android.view.WindowManager;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Spinner;
import android.widget.TextView;

import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;

public class SendUserCircleCode extends DialogFragment {

    public SendUserCircleCode(){

    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View view = null;
        final FirebaseDatabase database;

        try {
            TextView circleCodeTextView = (TextView) view.findViewById(R.id.textView);

            // getting the view layout from fragment_sendcode
            view = inflater.inflate(R.layout.fragment_sendcode, container);

            // Global database references
            DatabaseReference userDatabaseReference;
            FirebaseUser user = FirebaseAuth.getInstance().getCurrentUser();
            database = FirebaseDatabase.getInstance();

            // UID string based on the current logged on user
            String uid = user.getUid();

            // Defining the reference's location on the database
            userDatabaseReference = database.getReference().child("UserData").child(uid);

            // circle string that holds the value of the circle is generated by the database
            String circleCode = database.getReference().push().getKey().toString();
            userDatabaseReference.child(uid).child("CircleCodes").setValue(circleCode);
            // Output the code to the text field
            circleCodeTextView.setText(circleCode);





            // Creates the dialog window
            final AlertDialog.Builder alertDialogBuilder = new AlertDialog.Builder(getActivity());
            getDialog().getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_VISIBLE);
            alertDialogBuilder.setTitle("Circle Code.").create();

        } catch (Exception e) {
            e.printStackTrace();
        }
        return view;
    }
}
